fit/urls.py
from django.urls import path
from . import views
app_name='fit'

urlpatterns = [
    path('',views.index,name='index'),
    path('film/',views.show,name='show'),
    path('movie/',views.movie,name='movie'),
    path('topics/',views.topics,name='topics'),
    path('new_topics/',views.new_topics,name='new_topics'), 
    
    
]

rose/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('fit.urls')),
    path('users/',include('users.urls')),
]

users/urls.py
from django.urls import path,include
from . import views
app_name='users'

urlpatterns = [
     
    path('',include('django.contrib.auth.urls')),
    path('register/',views.register,name='register'),
]

fit/models.py
from django.db import models

# Create your models here.
class Topic(models.Model): 
    title=models.TextField()
    date_add=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title
class User(models.Model):
    name=models.CharField(max_length=20)
    number=models.IntegerField() 
    time=models.DateTimeField()   

users/models.py
from django.db import models

# Create your models here.

fit/forms.py
from django.forms import ModelForm
from .models import Topic 
class TopicForm(ModelForm):
    class Meta:
        model=Topic
        fields=('title',)
  

fit/views.py
from django.shortcuts import render,redirect
from .models import Topic
from .forms import TopicForm
# Create your views here.
def index(request):
    return render(request,'fit/index.html')
def show(request):
    return render(request,'fit/show.html') 
def movie(request):
    return render(request,'fit/movie.html')              
def topics(request):
    topics=Topic.objects.order_by('date_add')  
    context={'topics':topics} 
    return render(request,'fit/topics.html',context) 
def new_topics(request):
    if request.method =='POST':   
        form=TopicForm(request.POST) 
        if form.is_valid():
            form.save()
            return redirect('fit:topics')
    else:
        form=TopicForm()
    return render(request,'fit/new_topics.html',{'form':form})   
           
def test_comment(request):
    

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
# Create your views here.
def register(request):
    if request.method !='POST':
        form=UserCreationForm()
    else:
        form=UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user=form.save()
            login(request,new_user)
            return redirect('fit:index')
    context={'form':form} 
    return render(request,'registration/register.html',context)       
            
            
        
            
    

fit/templates/fit/index.html
<html>
 <head>
  
  <style>
  #d2
  {
   width:737px;
   height:460px;
   background:linear-gradient(black,rgba(0,0,139));
   margin:0 auto 0;
   margin-bottom:10px;
  }
    
  #d1
   {
    width:130px;
    height:455px;
    background:linear-gradient(rgb(72,209,204),black,rgb(139,0,139));
    padding:0px 0px 0px 0px;
    margin:0px 0px 0px 0px ;
    border:2px solid black;
    float:left;
   }
   ul
   {
    list-style-type:none;
    
   }
   li a
   {
    text-decoration:none;
    display:block;
    padding:20px 0px 0px 0px;
    
    
   }
   li a:hover
   {
    color:gold;
    font-size:22px;
   }
   a
   {
    position:relative;
    right:26px; 
    font-size:20px;
    color:rgb(255,255,255);
    font-weight:bold;
    
    
   }
   
   #d3
   {
    width:150px;
    height:70px;
    background:linear-gradient(orange,rgb(224,255,255));
    float:left;
    position:relative;
    left:395px;
    top:27px;
    border-radius:30px;
    text-align:center;
    transition: transform 2s ;
    
   }
   #d3:hover
   {
    transform:rotate(-30deg);
   }
  p
  {
   font-size:17px;
   color:black;
   font-weight:bold;
  }
  #d4
  {
   width:180px;
   height:100px;
   background-color:rgba(230,230,250);
   float:left;
   position:relative;
   top:300;
   left:184px;
    border:3px solid black;
  }
  #d4 a
  {
   position:relative;
   font-size:24px;
   top:20px; 
   left:42px;
   text-decoration:none;
   color:gold;
 
  }
 #d4 a:hover
 {
  color:black;
  font-size:24px; 
 } 
 #d5
 {
 
 
  position:relative;
  right:300px;
  bottom:200px;
  
 }
  </style>
 </haed>
 <body>
  <div id="d2">
    <div id="d1">
      <ul>
       <li> <a href="{% url 'fit:topics'  %}"> idea </a></li>
       <li> <a href="{% url 'fit:show'%}"> pictiures  </a> </li>
       <li> <a href="{% url 'fit:movie' %}"> movie</a> </li>
       
       
      </ul> 
    </div>
    <div id="d3">
     <p> welcome</p>
    </div> 
    <div id="d4">
      {% if user.is_authenticated %}
          <span style="font-size:15px;font-weight:bold;">HELLO {{ user.username}}.</span>
         <a href="{% url 'users:logout' %}"> logout </a>   
      {% else %}
         <a href="{% url 'users:login' %}"> login </a>
        <div id="d5"> 
         <a href="{%url 'users:register'%}"> Register </a>
        </div>  
      {% endif %} 
    </div>
  </div>
  
 </body>
</html>

fit/templates/fit/movie.html
<html>
 <head>
   <style>
  
   </style>
 </head>
 <body>
   <video width:"120" height:"100" >
     <source src="https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiv-Inti-rvAhVIr6QKHRrwCo0QwqsBMAJ6BAgCEA0&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DBPXxdFM32mU&usg=AOvVaw0hJEW7_wgdR9NISkGet4YN"type="video/mp4"  />
   </video>
   
  </div>
 </body>
</html>

fit/templates/fit/new_topics.html
<html>
 <haed>
 </head>
 <body>

  <p> add your idea </p>
  <form action="" method='post'>
  {% csrf_token %}
  {{form.as_p}}
   <button type='submit'> new idea </button> 
  </form>
  
  
 </body>
</html>

fit/templates/fit/show.html
<html>
 <head>
  <style>
   #d1
   {
    width:710px;
    height:1400px;
    background-color:black;
    padding:0 auto 0;
    border:2px solid black;
     
 }
 #d1 a
 {
  font-size:22px;
  color:gold;
  font-weight:bold;
  text-decoration:none;
  position:relative;
  top:5px;
  left:60px;
  font-style:italic;
 }
#d1 a:hover
{
 color:rgb(255,255,255);
}
 #p1
 {
  float:left;
  
 }
 #p2
 {
 height:200px;
 float:left;
 position:relative;
 top:0px;
 left:390px;
 border:4px inset rgb(255,255,255);
 }
 #p3
 {
 float:left;
 width:340px;
 height:300px;
 position:relative;
 right:270px;
  border:4px inset rgb(255,255,255);
 }
 #p4
 {
  position:relative;
  left:36px;
  top:18px;
  height:200px;
  border:4px inset rgb(255,255,255);
 }
  </style>
 </head>
 <body>
   <div id="d1">
      <a href="{%url 'fit:index' %}"> HOME </a>
      <img id="p1" src="https://images.theconversation.com/files/222720/original/file-20180612-52455-d6et0u.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=496&fit=clip">
      <img id="p2" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGSWGYD-olYdkE3mkIRLhFLJNycELrAveWh2XKLyPAlT3W6nACeIe6iGRI4tyicd64kJE&usqp=CAU">
      <img id="p3" src="https://i.pinimg.com/originals/c2/84/e3/c284e31f7c546e033bdcbe5900a44843.jpg">
      <img id="p4" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiWDSaExK29eIse1t-o2nBnzqx22zaYbI-fhQnmXlKSYY55B9G97LeZ4TCT1NzoE6kAeY&usqp=CAU">
      
     </div>
   </div> 
 </body>
</html>

fit/templates/fit/topics.html
<html>
 <head>
  
  <style>
   #d1
   {
    width:710px;
    height:470px;
    margin:0 auto 0;
    background:linear-gradient(rgba(0,0,128),rgb(50,205,50),black);
  
    
   }
   @-webkit-keyframes a1
   {
    to{
    width:200px;
    height:100px;
    background:linear-gradient(orange,rgb(224,255,255));
    position:relative;
    left:400px;
    top:40px;
    border:4px solid black; 
   
    }
    from
    {
    width:400px;
    height:300px;
    background:linear-gradient(orange,rgb(224,255,255));
    position:relative;
    left:400px;
    top:40px;
    border:4px solid black; 
    transform:rotate(60deg);
    
    
    
    }
   }
   #d2
   {
    width:200px;
    height:100px;
    background:linear-gradient(orange,rgb(224,255,255));
    position:relative;
    left:450px;
    top:40px;
    border:4px solid black; 
    -webkit-animation:a1 4s;
    -webkit-animation-interation-count:2;
    text-align:center;
    font-size:24px;
    font-weight:bold;
    font-style:italic;
    
    
   }
   #d2:hover
   {
    transform:rotate(-50deg);
   
    background:linear-gradient(red,rgb(224,255,255));
   }
   ul
   {
    
   list-style-type:none;
   
   }
   li
   {
    font-weight:bold;
    color:black;
    font-size:19px;
    font-style:italic;
   }
   a
   {
    font-size:20px;
    color:red;
    font-weight:bold;
    text-decoration:none;
    position:relative;
    left:20px;
   }
   a:hover
   {
    font-size:23px;
    color:rgb(255,255,255);
   }
   #d3
   {
    width:100px;
    height:40px;
    background-color:black;
    border-radius:40px;
    top:10px;
    margin-top:0px;
   }
   #d3 a
   {
    text-align:center;
    position:relative;
    top:2px;
    font-size:15px;
    color:gold;
   }
 #d3 a:hover
 {
  
  color:rgb(255,255,255);
 }  
  </style>
 </head>
 <body>
 
  <div id="d1">
    <div id="d3">
      <a href="{%url 'fit:index' %}"> HOME </a>
   </div>
   <div id="d2">
     coments
   </div> 
   
   <ul>
    {% for topic in topics %}
      <li> {{topic}} </li>
    {% empty %}
      <li> no have been yet </li>
    {% endfor %} 
   </ul>
   <a href="{% url 'fit:new_topics'  %}"> add idea </a>
  </div>
 </body>
</html>